/* AUTO-GENERATED by Sidbox IDE GUI Designer.
   Target: SIDBOX applet API (apis.h), not firmware-private CoderGirl headers.
   Edit USER blocks only; designer regeneration replaces generated sections. */

#include "apis.h"
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#ifndef GAD_TOOL_TRANSPARENT
#define GAD_TOOL_TRANSPARENT (1u << 16)
#endif

extern const uint8_t optionswindow_zappsound_pcm[];
extern const uint32_t optionswindow_zappsound_pcm_length;
extern uint8_t optionswindow_bitmap1_pixels[];
extern uint8_t optionswindow_bitmap3_pixels[];
extern uint8_t optionswindow_bitmap4_pixels[];

extern void MainWindow_Create(void);

static CGWindow OptionsWindow;
static uint8_t OptionsWindow_is_open = 0u;
static CGWindow OptionsWindow_active_dialog = (CGWindow)0xFFu;
static uint8_t OptionsWindow_dialog_block_owner = 0u;
static CGTimer timer1 = CGTIMER_INVALID;
static CGGadget bitmap1;
static CGGadget btn2;
static CGGadget bitmap2;
static CGGadget canvas1;
static CGGadget lbl1;
static CGGadget btn1;
static CGGadget bitmap3;
static CGGadget bitmap4;
static CGGadget chk1;
static CGGadget btn3;
static CGGadget prg1;
static CGGadget rad1;
static CGGadget rad2;
static CGGadget lbl2;
static CGGadget btn4;
static CGGadget btn5;
static CGGadget txt1;
static CGGadget btn6;
static CGGadget prg2;
static CGGadget lbl3;
static CGGadget bitmap2_tab_0;
static CGGadget bitmap2_tab_1;
static CGGadget bitmap2_tab_2;
static CGWindow fileRequest1_requester = (CGWindow)0xFFu;
static CGWindow messageBox1_requester = (CGWindow)0xFFu;
static char fileRequest1_initial_dir[] = "sdcard:/";
static char fileRequest1_selected_path[FILERQ_OUTCAP];

static void OptionsWindow_SetDialogOwnerBlocked(uint8_t blocked)
{
	if (OptionsWindow_dialog_block_owner == (blocked ? 1u : 0u)) return;
	OptionsWindow_dialog_block_owner = blocked ? 1u : 0u;
	if (blocked) SBOS_WindowDisable(OptionsWindow);
	else SBOS_WindowEnable(OptionsWindow);
}

static void fileRequest1_Show(void)
{
	if (OptionsWindow_active_dialog != (CGWindow)0xFFu) return;
	CGWindow requester;
	requester = SBOS_FileRequestFilter(OptionsWindow, "Select a file", fileRequest1_initial_dir, "*.*");
	if (requester == (CGWindow)0xFFu) return;
	OptionsWindow_active_dialog = requester;
	fileRequest1_requester = requester;
	OptionsWindow_SetDialogOwnerBlocked(1u);
}

static void messageBox1_Show(void)
{
	if (OptionsWindow_active_dialog != (CGWindow)0xFFu) return;
	CGWindow requester;
	requester = SBOS_MessageBox(OptionsWindow, "Confirmation", "Are you sure?", MSGBOXF_YESNO);
	if (requester == (CGWindow)0xFFu) return;
	OptionsWindow_active_dialog = requester;
	messageBox1_requester = requester;
	OptionsWindow_SetDialogOwnerBlocked(1u);
}


static char media_music_file[] = "amegas.mod";
static uint8_t media_music_active = 0u;
static void media_music_Play(void)
{
	music_play(media_music_file, 0u);
	media_music_active = 1u;
}
static void media_music_Stop(void)
{
	if (!media_music_active) return;
	music_stop();
	media_music_active = 0u;
}
/* NOTE: call music_update() from your applet's cooperative main loop. */

static void zappsound_Play(void)
{
	sound_stop(0u);
	sound_assign(0u, optionswindow_zappsound_pcm, optionswindow_zappsound_pcm_length, SAMP_S8);
	sound_setfrequency(0u, 44100u);
	sound_setvolume(0u, 200u);
	sound_setpanning(0u, 0);
	sound_enableloop(0u, 0u);
	sound_play(0u);
}
static void zappsound_Stop(void)
{
	sound_stop(0u);
}
static void zappsound_Cleanup(void)
{
	sound_stop(0u);
	sound_assign(0u, NULL, 0u, SAMP_S8);
}

static CGWindowProcRes OptionsWindow_WindowProc(CGWindow win, const CGMessage_t *m);
static void OptionsWindow_bitmap2_SIDBOX_OnTab(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_fileRequest1_Selected(const char *path);
static void On_fileRequest1_Cancelled(void);
static void On_messageBox1_Result(int32_t result);
static void On_bitmap1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_bitmap1_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_btn2_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_canvas1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_btn1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_bitmap3_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_bitmap3_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_bitmap4_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_bitmap4_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_chk1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_chk1_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_btn3_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_rad1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_rad1_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_rad2_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_rad2_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_btn4_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_btn5_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_txt1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_txt1_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_btn6_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d);
static void On_timer1_Tick(void *user);
static void SidboxDirect_On_btn2_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_canvas1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_btn1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_bitmap3_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_bitmap3_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_bitmap4_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_bitmap4_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_chk1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_chk1_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_btn3_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_rad1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_rad1_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_rad2_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_rad2_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_btn4_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_btn5_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_txt1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_txt1_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_btn6_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d);
static void SidboxDirect_On_btn2_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_btn2_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_canvas1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_canvas1_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_btn1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_btn1_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_bitmap3_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_bitmap3_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_bitmap3_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_bitmap3_Change(gadget, a, b, c, d);
}

static void SidboxDirect_On_bitmap4_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_bitmap4_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_bitmap4_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_bitmap4_Change(gadget, a, b, c, d);
}

static void SidboxDirect_On_chk1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_chk1_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_chk1_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_chk1_Change(gadget, a, b, c, d);
}

static void SidboxDirect_On_btn3_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_btn3_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_rad1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_rad1_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_rad1_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_rad1_Change(gadget, a, b, c, d);
}

static void SidboxDirect_On_rad2_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_rad2_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_rad2_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_rad2_Change(gadget, a, b, c, d);
}

static void SidboxDirect_On_btn4_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_btn4_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_btn5_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_btn5_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_txt1_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_txt1_Activate(gadget, a, b, c, d);
}

static void SidboxDirect_On_txt1_Change(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_txt1_Change(gadget, a, b, c, d);
}

static void SidboxDirect_On_btn6_Activate(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	const CGGadget gadget = source
		? API->gui->gadgets->get_id(source)
		: (CGGadget)0u;
	On_btn6_Activate(gadget, a, b, c, d);
}

static void OptionsWindow_bitmap2_SIDBOX_OnTab(void *source, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)a; (void)b; (void)c; (void)d;
	const CGGadget clicked = API->gui->gadgets->get_id(source);
	if (clicked == bitmap2_tab_0) {
		API->gui->gadgets->set_group_visible(OptionsWindow, 1u, 1u);
		API->gui->gadgets->set_group_visible(OptionsWindow, 2u, 0u);
		API->gui->gadgets->set_group_visible(OptionsWindow, 3u, 0u);
		API->gui->gadgets->button_set_toggle(bitmap2_tab_0, 1u);
		API->gui->gadgets->button_set_toggle(bitmap2_tab_1, 0u);
		API->gui->gadgets->button_set_toggle(bitmap2_tab_2, 0u);
	}
	else if (clicked == bitmap2_tab_1) {
		API->gui->gadgets->set_group_visible(OptionsWindow, 1u, 0u);
		API->gui->gadgets->set_group_visible(OptionsWindow, 2u, 1u);
		API->gui->gadgets->set_group_visible(OptionsWindow, 3u, 0u);
		API->gui->gadgets->button_set_toggle(bitmap2_tab_0, 0u);
		API->gui->gadgets->button_set_toggle(bitmap2_tab_1, 1u);
		API->gui->gadgets->button_set_toggle(bitmap2_tab_2, 0u);
	}
	else if (clicked == bitmap2_tab_2) {
		API->gui->gadgets->set_group_visible(OptionsWindow, 1u, 0u);
		API->gui->gadgets->set_group_visible(OptionsWindow, 2u, 0u);
		API->gui->gadgets->set_group_visible(OptionsWindow, 3u, 1u);
		API->gui->gadgets->button_set_toggle(bitmap2_tab_0, 0u);
		API->gui->gadgets->button_set_toggle(bitmap2_tab_1, 0u);
		API->gui->gadgets->button_set_toggle(bitmap2_tab_2, 1u);
	}
}

// $IDE:OpenWindow //
void OptionsWindow_Create(void)
{
	if (OptionsWindow_is_open) {
		SBOS_WindowToFront(OptionsWindow);
		SBOS_WindowSetFocus(OptionsWindow);
		return;
	}

	OptionsWindow = SBOS_CreateWindow(&OptionsWindow, 24, 12, 405, 298, "Ye ol'e Options Test", SBX_WF_VISIBLE | SBX_WF_CLOSE | SBX_WF_TITLE_BAR | SBX_WF_ZORDER | SBX_WF_MINIMISE | SBX_WF_SCREENBOUND | SBX_WF_MOVEABLE);
	if (OptionsWindow == (CGWindow)0xFFu) {
		return;
	}
	OptionsWindow_is_open = 1u;
	OptionsWindow_active_dialog = (CGWindow)0xFFu;
	OptionsWindow_dialog_block_owner = 0u;
	fileRequest1_requester = (CGWindow)0xFFu;
	messageBox1_requester = (CGWindow)0xFFu;
	SBOS_SetWindowProc(OptionsWindow, OptionsWindow_WindowProc);
	/* Window background pen 1 is stored by the designer.
	   The current public applet API does not export window_set_back_colour yet. */

	bitmap2 = API->gui->gadgets->canvas_create(OptionsWindow, 4, 28, 389, 205, CNV_BEVEL, GAD_TOOL_INSET);
	API->gui->gadgets->set_group_id(bitmap2, 0u);
	bitmap2_tab_0 = API->gui->gadgets->button_create(OptionsWindow, 4, 4, 129, 24, "General", GAD_TOOL_DEFAULT | GAD_TOOL_TOGGLE);
	API->gui->gadgets->set_group_id(bitmap2_tab_0, 0u);
	API->gui->gadgets->set_callback(bitmap2_tab_0, OptionsWindow_bitmap2_SIDBOX_OnTab, NULL);
	bitmap2_tab_1 = API->gui->gadgets->button_create(OptionsWindow, 133, 4, 129, 24, "Advanced", GAD_TOOL_DEFAULT | GAD_TOOL_TOGGLE);
	API->gui->gadgets->set_group_id(bitmap2_tab_1, 0u);
	API->gui->gadgets->set_callback(bitmap2_tab_1, OptionsWindow_bitmap2_SIDBOX_OnTab, NULL);
	bitmap2_tab_2 = API->gui->gadgets->button_create(OptionsWindow, 262, 4, 131, 24, "RequesterTest", GAD_TOOL_DEFAULT | GAD_TOOL_TOGGLE);
	API->gui->gadgets->set_group_id(bitmap2_tab_2, 0u);
	API->gui->gadgets->set_callback(bitmap2_tab_2, OptionsWindow_bitmap2_SIDBOX_OnTab, NULL);
	API->gui->gadgets->set_bpen(bitmap2, 2);
	API->gui->gadgets->set_group_id(bitmap2, 0u);
	API->gui->gadgets->enabled(bitmap2, 1u);
	API->gui->gadgets->repaint(bitmap2);

	bitmap1 = API->gui->gadgets->bitmapview_create(OptionsWindow, 8, 32, 380, 196, 380, 196, BVF_SHOW_FRAME | BVF_SRC_ROWMAJOR, GAD_TOOL_INSET);
	SBOS_BitmapviewSetBitmap(bitmap1, optionswindow_bitmap1_pixels);
	SBOS_BitmapviewSetImageSize(bitmap1, 380, 196);
	API->gui->gadgets->set_group_id(bitmap1, 1u);
	API->gui->gadgets->enabled(bitmap1, 1u);
	API->gui->gadgets->repaint(bitmap1);

	btn2 = API->gui->gadgets->button_create(OptionsWindow, 8, 244, 90, 22, "Button", GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(btn2, 0u);
	API->gui->gadgets->enabled(btn2, 1u);
	API->gui->gadgets->set_callback(btn2, SidboxDirect_On_btn2_Activate, NULL);
	API->gui->gadgets->repaint(btn2);

	canvas1 = API->gui->gadgets->canvas_create(OptionsWindow, 200, 244, 191, 22, CNV_BEVEL, GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_bpen(canvas1, 2);
	API->gui->gadgets->set_group_id(canvas1, 0u);
	API->gui->gadgets->enabled(canvas1, 1u);
	API->gui->gadgets->set_callback(canvas1, SidboxDirect_On_canvas1_Activate, NULL);
	API->gui->gadgets->repaint(canvas1);

	lbl1 = API->gui->gadgets->label_create(OptionsWindow, 204, 247, 124, 14, "Sausages!", GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(lbl1, 0u);
	API->gui->gadgets->enabled(lbl1, 1u);
	API->gui->gadgets->repaint(lbl1);

	btn1 = API->gui->gadgets->button_create(OptionsWindow, 100, 244, 90, 22, "Close", GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(btn1, 0u);
	API->gui->gadgets->enabled(btn1, 1u);
	API->gui->gadgets->set_callback(btn1, SidboxDirect_On_btn1_Activate, NULL);
	API->gui->gadgets->repaint(btn1);

	bitmap3 = API->gui->gadgets->bitmapview_create(OptionsWindow, 8, 32, 161, 81, 160, 80, BVF_SHOW_FRAME | BVF_SRC_ROWMAJOR, GAD_TOOL_INSET);
	SBOS_BitmapviewSetBitmap(bitmap3, optionswindow_bitmap3_pixels);
	SBOS_BitmapviewSetImageSize(bitmap3, 160, 80);
	API->gui->gadgets->set_group_id(bitmap3, 2u);
	API->gui->gadgets->enabled(bitmap3, 1u);
	API->gui->gadgets->set_callback(bitmap3, SidboxDirect_On_bitmap3_Activate, SidboxDirect_On_bitmap3_Change);
	API->gui->gadgets->repaint(bitmap3);

	bitmap4 = API->gui->gadgets->bitmapview_create(OptionsWindow, 224, 32, 165, 197, 164, 197, BVF_SHOW_FRAME | BVF_SRC_ROWMAJOR, GAD_TOOL_INSET);
	SBOS_BitmapviewSetBitmap(bitmap4, optionswindow_bitmap4_pixels);
	SBOS_BitmapviewSetImageSize(bitmap4, 164, 197);
	API->gui->gadgets->set_group_id(bitmap4, 2u);
	API->gui->gadgets->enabled(bitmap4, 1u);
	API->gui->gadgets->set_callback(bitmap4, SidboxDirect_On_bitmap4_Activate, SidboxDirect_On_bitmap4_Change);
	API->gui->gadgets->repaint(bitmap4);

	chk1 = API->gui->gadgets->checkbox_create(OptionsWindow, 12, 208, 130, 20, "Checkbox", 0, GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(chk1, 2u);
	API->gui->gadgets->enabled(chk1, 1u);
	API->gui->gadgets->set_callback(chk1, SidboxDirect_On_chk1_Activate, SidboxDirect_On_chk1_Change);
	API->gui->gadgets->repaint(chk1);

	btn3 = API->gui->gadgets->button_create(OptionsWindow, 8, 116, 161, 22, "Do Sound!", GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(btn3, 2u);
	API->gui->gadgets->enabled(btn3, 1u);
	API->gui->gadgets->set_callback(btn3, SidboxDirect_On_btn3_Activate, NULL);
	API->gui->gadgets->repaint(btn3);

	prg1 = API->gui->gadgets->progbar_create(OptionsWindow, 12, 144, 157, 24, GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(prg1, 2u);
	API->gui->gadgets->enabled(prg1, 1u);
	API->gui->gadgets->progressbar_set_minmax(prg1, 0, 100);
	API->gui->gadgets->progressbar_set_value(prg1, 50);
	API->gui->gadgets->repaint(prg1);

	rad1 = API->gui->gadgets->radiobutton_create(OptionsWindow, 176, 32, 33, 20, "1", 0, 1, GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(rad1, 2u);
	API->gui->gadgets->enabled(rad1, 1u);
	API->gui->gadgets->set_callback(rad1, SidboxDirect_On_rad1_Activate, SidboxDirect_On_rad1_Change);
	API->gui->gadgets->repaint(rad1);

	rad2 = API->gui->gadgets->radiobutton_create(OptionsWindow, 176, 52, 33, 20, "2", 0, 0, GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(rad2, 2u);
	API->gui->gadgets->enabled(rad2, 1u);
	API->gui->gadgets->set_callback(rad2, SidboxDirect_On_rad2_Activate, SidboxDirect_On_rad2_Change);
	API->gui->gadgets->repaint(rad2);

	lbl2 = API->gui->gadgets->label_create(OptionsWindow, 16, 204, 169, 16, "needs transparencies", GAD_TOOL_DEFAULT | GAD_TOOL_TRANSPARENT);
	API->gui->gadgets->set_bpen(lbl2, 16);
	API->gui->gadgets->set_fpen(lbl2, 16);
	API->gui->gadgets->set_group_id(lbl2, 1u);
	API->gui->gadgets->enabled(lbl2, 1u);
	API->gui->gadgets->repaint(lbl2);

	btn4 = API->gui->gadgets->button_create(OptionsWindow, 12, 176, 157, 22, "Play Zapp", GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(btn4, 2u);
	API->gui->gadgets->enabled(btn4, 1u);
	API->gui->gadgets->set_callback(btn4, SidboxDirect_On_btn4_Activate, NULL);
	API->gui->gadgets->repaint(btn4);

	btn5 = API->gui->gadgets->button_create(OptionsWindow, 12, 36, 90, 22, "FileReq", GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(btn5, 3u);
	API->gui->gadgets->enabled(btn5, 1u);
	API->gui->gadgets->set_callback(btn5, SidboxDirect_On_btn5_Activate, NULL);
	API->gui->gadgets->repaint(btn5);

	txt1 = API->gui->gadgets->textbox_create(OptionsWindow, 108, 36, 273, 22, "Text", (0u), GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(txt1, 3u);
	API->gui->gadgets->enabled(txt1, 1u);
	API->gui->gadgets->set_callback(txt1, SidboxDirect_On_txt1_Activate, SidboxDirect_On_txt1_Change);
	API->gui->gadgets->repaint(txt1);

	btn6 = API->gui->gadgets->button_create(OptionsWindow, 12, 72, 90, 22, "MsgBox", GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(btn6, 3u);
	API->gui->gadgets->enabled(btn6, 1u);
	API->gui->gadgets->set_callback(btn6, SidboxDirect_On_btn6_Activate, NULL);
	API->gui->gadgets->repaint(btn6);

	prg2 = API->gui->gadgets->progbar_create(OptionsWindow, 16, 100, 369, 24, GAD_TOOL_DEFAULT);
	API->gui->gadgets->set_group_id(prg2, 3u);
	API->gui->gadgets->enabled(prg2, 1u);
	API->gui->gadgets->progressbar_set_minmax(prg2, 0, 100);
	API->gui->gadgets->progressbar_set_value(prg2, 50);
	API->gui->gadgets->repaint(prg2);

	lbl3 = API->gui->gadgets->label_create(OptionsWindow, 14, 202, 169, 16, "needs transparencies", GAD_TOOL_DEFAULT | GAD_TOOL_TRANSPARENT);
	API->gui->gadgets->set_bpen(lbl3, 16);
	API->gui->gadgets->set_fpen(lbl3, 2);
	API->gui->gadgets->set_group_id(lbl3, 1u);
	API->gui->gadgets->enabled(lbl3, 1u);
	API->gui->gadgets->repaint(lbl3);

	API->gui->gadgets->set_group_visible(OptionsWindow, 1u, 1u);
	API->gui->gadgets->button_set_toggle(bitmap2_tab_0, 1u);
	API->gui->gadgets->set_group_visible(OptionsWindow, 2u, 0u);
	API->gui->gadgets->button_set_toggle(bitmap2_tab_1, 0u);
	API->gui->gadgets->set_group_visible(OptionsWindow, 3u, 0u);
	API->gui->gadgets->button_set_toggle(bitmap2_tab_2, 0u);
	SBOS_WindowToFront(OptionsWindow);
	SBOS_WindowSetFocus(OptionsWindow);
	API->gui->gadgets->repaint(bitmap1);
	API->gui->gadgets->repaint(bitmap3);
	API->gui->gadgets->repaint(bitmap4);
	timer1 = SBOS_CreateTimer();
}

static CGWindowProcRes OptionsWindow_WindowProc(CGWindow win, const CGMessage_t *m)
{
	if (!m) {
		return CGPROC_DEFAULT;
	}

	switch (m->mtype) {
	case CGMSG_WINDOW:
		switch (m->eventClass) {
		case CGEVT_WIN_CLOSE_REQUEST:
			/* Keep the owner alive until its non-modal dialog completes. */
			if (OptionsWindow_active_dialog != (CGWindow)0xFFu) return CGPROC_HANDLED;
			/* <SIDBOX-GUI:USER WINDOW_CLOSE> */
			/* Put close-validation/user shutdown code here. */
			/* </SIDBOX-GUI:USER WINDOW_CLOSE> */
			media_music_Stop();
			zappsound_Cleanup();
			if (timer1 != CGTIMER_INVALID) {
				SBOS_TimerCancel(timer1);
				SBOS_FreeTimer(timer1);
				timer1 = CGTIMER_INVALID;
			}
			OptionsWindow_is_open = 0u;
			SBOS_CloseWindow(win);
			return CGPROC_HANDLED;

		case CGEVT_SYS_REPAINT:
			/* BitmapViews must be restored after a system/window repaint. */
			API->gui->gadgets->repaint(bitmap1);
			API->gui->gadgets->repaint(bitmap3);
			API->gui->gadgets->repaint(bitmap4);
			/* Keep CoderGirl default dirty-rect/compositor processing. */
			return CGPROC_DEFAULT;

		case CGEVT_SYS_FILERQ_DONE:
			if (OptionsWindow_active_dialog == (CGWindow)m->d && fileRequest1_requester == (CGWindow)m->d) {
				OptionsWindow_active_dialog = (CGWindow)0xFFu;
				fileRequest1_requester = (CGWindow)0xFFu;
				if (OptionsWindow_dialog_block_owner) OptionsWindow_SetDialogOwnerBlocked(0u);
				if (m->a && m->c) {
					const char *src = MSG_AS_PTR(const char, m->c);
					uint32_t i = 0u;
					for (; i + 1u < sizeof(fileRequest1_selected_path) && src[i]; ++i)
						fileRequest1_selected_path[i] = src[i];
					fileRequest1_selected_path[i] = 0;
					On_fileRequest1_Selected(fileRequest1_selected_path);
				} else { On_fileRequest1_Cancelled(); }
				return CGPROC_HANDLED;
			}
			break;
		case CGEVT_SYS_MSGBOX_DONE:
			if (OptionsWindow_active_dialog == (CGWindow)m->d && messageBox1_requester == (CGWindow)m->d) {
				OptionsWindow_active_dialog = (CGWindow)0xFFu;
				messageBox1_requester = (CGWindow)0xFFu;
				if (OptionsWindow_dialog_block_owner) OptionsWindow_SetDialogOwnerBlocked(0u);
				On_messageBox1_Result(m->a);
				return CGPROC_HANDLED;
			}
			break;
		case CGEVT_SYS_INFOBOX_DONE:
			break;

		default:
			break;
		}
		break;

	case CGMSG_GADGET:
		if (OptionsWindow_dialog_block_owner) return CGPROC_HANDLED;
		switch (m->eventClass) {
		case CGEVT_GAD_ACTIVATED:
			if (m->gadget == bitmap1) {
				On_bitmap1_Activate(m->gadget, m->a, m->b, m->c, m->d);
				return CGPROC_HANDLED;
			}
			break;

		case CGEVT_GAD_MOUSE_MOVE:
			if (m->gadget == bitmap1) {
				On_bitmap1_Change(m->gadget, m->a, m->b, m->c, m->d);
				return CGPROC_HANDLED;
			}
			break;

		default:
			break;
		}
		break;

	default:
		break;
	}

	/* Returning DEFAULT lets CoderGirl perform its normal window behaviour. */
	return CGPROC_DEFAULT;
}

static void On_bitmap1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_bitmap1_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_bitmap1_Activate> */
}

static void On_bitmap1_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_bitmap1_Change> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_bitmap1_Change> */
}

static void On_btn2_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	MainWindow_Create();
	/* <SIDBOX-GUI:USER On_btn2_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_btn2_Activate> */
}

static void On_canvas1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_canvas1_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_canvas1_Activate> */
}

static void On_btn1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_btn1_Activate> */
	/* TODO: programmer callback code */
	SBOS_CloseWindow(OptionsWindow);
	OptionsWindow_is_open = 0u;
	/* </SIDBOX-GUI:USER On_btn1_Activate> */
}

static void On_bitmap3_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_bitmap3_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_bitmap3_Activate> */
}

static void On_bitmap3_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_bitmap3_Change> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_bitmap3_Change> */
}

static void On_bitmap4_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_bitmap4_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_bitmap4_Activate> */
}

static void On_bitmap4_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_bitmap4_Change> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_bitmap4_Change> */
}

static void On_chk1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_chk1_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_chk1_Activate> */
}

static void On_chk1_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_chk1_Change> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_chk1_Change> */
}

static void On_btn3_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	media_music_Stop();
	/* <SIDBOX-GUI:USER On_btn3_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_btn3_Activate> */
}

static void On_rad1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_rad1_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_rad1_Activate> */
}

static void On_rad1_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_rad1_Change> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_rad1_Change> */
}

static void On_rad2_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_rad2_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_rad2_Activate> */
}

static void On_rad2_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_rad2_Change> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_rad2_Change> */
}

static void On_btn4_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	zappsound_Play();
	/* <SIDBOX-GUI:USER On_btn4_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_btn4_Activate> */
}

static void On_btn5_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	fileRequest1_Show();
	/* <SIDBOX-GUI:USER On_btn5_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_btn5_Activate> */
}

static void On_txt1_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_txt1_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_txt1_Activate> */
}

static void On_txt1_Change(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	/* <SIDBOX-GUI:USER On_txt1_Change> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_txt1_Change> */
}

static void On_btn6_Activate(CGGadget gadget, int32_t a, int32_t b, int32_t c, int32_t d)
{
	(void)gadget; (void)a; (void)b; (void)c; (void)d;
	if (OptionsWindow_dialog_block_owner) return;
	messageBox1_Show();
	/* <SIDBOX-GUI:USER On_btn6_Activate> */
	/* TODO: programmer callback code */
	/* </SIDBOX-GUI:USER On_btn6_Activate> */
}

static void On_timer1_Tick(void *user)
{
	(void)user;
	/* <SIDBOX-GUI:USER On_timer1_Tick> */
	/* TODO: timer tick; keep callbacks cooperative and short. */
	printf("hello world\n");
	/* </SIDBOX-GUI:USER On_timer1_Tick> */
}

static void On_fileRequest1_Selected(const char *path)
{
	/*
	 * EXAMPLE ONLY (documentation; does not execute).
	 * The selected filename is supplied in 'path'.
	 * Copy the string to your own buffer if it must survive
	 * beyond this callback or after another file request.
	 *
	if (path && path[0] != '\0') {
		printf("[fileRequest1] Selected file: %s\n", path);
	} else {
		printf("[fileRequest1] Empty filename returned\n");
	}
	 */
	/* <SIDBOX-GUI:USER On_fileRequest1_Selected> */
	/* TODO: handle dialog result here. */
	SBOS_TextBoxSetText(txt1, path);
	/* </SIDBOX-GUI:USER On_fileRequest1_Selected> */
}

static void On_fileRequest1_Cancelled(void)
{
	/*
	 * EXAMPLE ONLY (documentation; does not execute).
	 * Cancel was pressed; no filename is returned.
	printf("[fileRequest1] File selection cancelled\n");
	 */
	/* <SIDBOX-GUI:USER On_fileRequest1_Cancelled> */
	/* TODO: handle dialog result here. */
	/* </SIDBOX-GUI:USER On_fileRequest1_Cancelled> */
}

static void On_messageBox1_Result(int32_t result)
{
	/*
	 * EXAMPLE ONLY (documentation; does not execute).
	 * The user's button choice is supplied in 'result'.
	 * Put your actual logic in the USER block below.
	 *
	switch (result) {
	case MSGBOX_OK:
		printf("[messageBox1] OK pressed\n");
		break;
	case MSGBOX_YES:
		printf("[messageBox1] YES pressed\n");
		break;
	case MSGBOX_NO:
		printf("[messageBox1] NO pressed\n");
		break;
	case MSGBOX_CANCEL:
		printf("[messageBox1] CANCEL pressed\n");
		break;
	default:
		printf("[messageBox1] Unknown result: %ld\n", (long)result);
		break;
	}
	 */
	/* <SIDBOX-GUI:USER On_messageBox1_Result> */
	/* TODO: handle dialog result here. */
	printf("Msgbox Result! %ld\n", (long)result);
	
	   if (result == MSGBOX_YES) {
	       printf("YES selected!\n");
	   }
	/* </SIDBOX-GUI:USER On_messageBox1_Result> */
}

/*
 * Preserved callbacks no longer referenced by the visual design.
 * They are disabled so deleting/renaming a gadget never destroys user code.
 */
#if 0
/* <SIDBOX-GUI:USER On_chk2_Activate> */
/* TODO: programmer callback code */
/* </SIDBOX-GUI:USER On_chk2_Activate> */

/* <SIDBOX-GUI:USER On_chk2_Change> */
/* TODO: programmer callback code */
/* </SIDBOX-GUI:USER On_chk2_Change> */

/* <SIDBOX-GUI:USER On_list1_Activate> */
/* TODO: programmer callback code */
/* </SIDBOX-GUI:USER On_list1_Activate> */

/* <SIDBOX-GUI:USER On_list1_Change> */
/* TODO: programmer callback code */
/* </SIDBOX-GUI:USER On_list1_Change> */

/* <SIDBOX-GUI:USER On_scroll1_Activate> */
/* TODO: programmer callback code */
/* </SIDBOX-GUI:USER On_scroll1_Activate> */

/* <SIDBOX-GUI:USER On_scroll1_Change> */
/* TODO: programmer callback code */
/* </SIDBOX-GUI:USER On_scroll1_Change> */

#endif
